id: PCEEE0E4E
initial_creation_type: input
source_metadata:
  Title: Vṛttamālāstuti of Jñānaśrīmitra with Śākyarakṣita’s Vṛttamālā(stuti)vivṛti
  Editor: Michael Hahn, S.S. Bahulkar, Lata Mahesh Deokar, M.A. Deokar
  Publisher: Deshana, Pune & Aditya Prakashan
  Place of Publication: New Delhi
  Year: '2016'
  वृत्तमालास्तुतिः:
    Text Version: Devanagari
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:17:45.666589'
last_modified_at: '2022-03-08T17:17:45.666600'
